# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '9.7.1'
  displayName: 'Install Node'

- script: brew install watchman
  displayName: 'Install Watchman'

- script: npm -g install react-native-cli
  displayName: 'Install React Native CLI'

- script: sudo gem install cocoapods
  displayName: 'Install CocoaPods'

- script: sudo gem install fastlane-2.107.0.gem -NV
  displayName: 'Install Fastlane'

- script: make build
  displayName: 'Build'
